== Control Information

[cols="^1,^2,^2,^2,^2"]
|===
.2+| *Version* 2+| *Delivery* 2+| *Feedback*
| _Deadline_ | _Delivered_ | _Received_ | _Integrated_ 

| **V1** | 29-08-2023 | 29-08-2023 | |
| **V2** | 01-09-2023 | | |
| **V3** | 15-09-2023 | | |
|===

[discrete]
=== Disclaimer

This document is written as an example of a _reasonable_ requirements document, using the temnplate defined by Bertrand Meyer in his _Handbook of Requirements and Business Analysis_ <<BM22>> (2022). 
It does not has the ambition of being a _perfect_ implementation of this template, as it mixes different sources and methods (e.g., <<RE97>>) to fit the objectives of COMPSCI/SFWRENG 3RA3 at McMaster. 
In addition of the two authors, this document is built on top of the expertise and discussions with Mireille Blay-Fornarino (Université Côte d'Azur), Jean-Michel Bruel (Université de Toulouse), and Richard Paige (McMaster University).

NOTE: In this document, we use _The Firebird_ as an **imaginary client**. The objective is to root the document into a concrete example for McMaster's students, which host since 1969 a restaurant with a _similar_ name. It is important to note that **this is a fictional case study**.  

[discrete]
=== Authors

[[tc,TC]]
Thomas Chiang.::
    Thomas is a Software Engineering PhD candidate at McMaster University, specialized in model driven engineering, language engineering, and safety engineering. His research interests are about improving safety engineering through model-driven engineering techniques, as well as developing principles for graphical modeling language development. You can reach him at {email_1}, and find more information here: https://www.linkedin.com/in/thomas-chiang-908362a1.

[[sm,SM]]
Sébastien Mosser, P.Eng., Ph.D.::
    Sébastien is Associate Professor of Software Engineering at McMaster University. His research interest are related to software engineering, more specifically language engineering and modelling in a DevOps context. He is teaching McMaster's Requirements Engineering (3RA3) course since Fall 2023, after having taught equivalent courses at _Université Côte d'Azur_ and _Université du Québec à Montréal_ since 2012. You can reach him at {email_2}, and find more information here: https://mosser.github.io

