[#g3,reftext=G.3]
=== (G.3) Expected Benefits

ifdef::env-draft[]
TIP: _New processes, or improvement to existing processes, made possible by the project’s results. It presents the business benefits expected from the successful execution of the project. **This chapter is the core of the Goals book**, describing what the organization expects from the system. It ensures that the project remains focused: if at some stage it gets pushed in different directions, with “creeping featurism” threatening its integrity, a reminder about the original business goals stated in those chapters will help._  <<BM22>>
endif::[]

The expected benefits of this app primarily center around increasing the on campus population. Despite the fact that Covid-19 is mostly under control, people are still generally shy to go out and be in person on campus with all of the new infrastructure allowing them to complete many of their tasks for school from the comfort of their home. However we have seen a sharp increase in people enjoying going out with their friends and family once the pandemic restrictions were lifted. Therefore the largest benefit that this app can bring is an increase in the on campus population. This is enabled for students by having the new take-out box system that allows students to order whenever and pick up warm and delicious food between classes easily as well as accepting student meal plan cards. It is also enabled by the integration with Mosaic to facilitate payment from departments and faculty for catering for events which can entice more people to be present for in-person events to enjoy the delicious food from the Firebird. Finally the loyalty program will incentivize repeat customers so that they can enjoy complimentary benefits at the Firebird! (note that the exact nature of the benefits has not been determined at the time of creating this document and will be refined at a later date.)

The goals that present these benefits, as well as the stakeholders that they affect can be seen in this goal model diagram:

.Goal model for the app
image::models/goal_model.svg[pdfwidth=100%,align="center"]

