[#g4,reftext=G.4]
=== (G.4) Functionality overview

ifdef::env-draft[]
TIP: _Overview of the functions (behavior) of the system. Principal properties only (details are in the System book). It is a short overview of the functions of the future system, a kind of capsule version of book S, skipping details but enabling readers to get a quick grasp of what the system will do._  <<BM22>>
endif::[]

The high level functional requirements for the application based on client input can be defined as follows in no particular order:

- *Integration with campus staff.* Client wants to be able to leverage the location of The Phoenix to allow McMaster's staff to order food for events directly through their internal information system and automatically support billing (instead of staff paying with their credit card and then submitting an expense report). This can be done primarily through Mosaic or something like Mosaic

- *Integration with campus life.* Client wants the app to facilitate student life ie. Enable students to easily access food in between classes and during busy periods like midterms and exams. This can be done by enabling food order in boxes and quick pickup in restaurant.

- *Attacting new customers.* Client hopes to use the app to encourage repeat customers. A loyalty program or card was given as an example to encourage patrons to enjoy The Phoenix patio during the summer, as well as points acquisition for potentially free appetizers during a visit. 

- *Device Compatibility.* To reach the broadest possible audience, the app that is being developed to be available across multiple operating systems and environments (Apple, Android, web browser).

- *Accepting meal plan cards* As part of the clients desire to integrate with Campus, having a payment method that accepts credit, debit, _and_ student meal cards is critical to the functionality of the app.

Of these functional requirements, 2 that are of critical importance is the integration with campus staff and integration with campus life. Integration with campus staff is critical to facilitate catering services of The Phoenix across campus through various system integrations. One of the main goals of the integrations is to reduce burden on staff for ordering catering services by having to pay out of pocket and then seek reimbursement from their department or faculty. Integration with campus life is another critical requirement to enable students to more efficiently get quality meals during particularly time-constrained periods of their studies, thus improving their quality of life during their stay at McMaster.

Some high level non-functional requirements for the application can be defined as follows in no particular order:

- *Compliance with McMaster University by-laws* 

- *Compliance with Ontario alcohol service laws and regulations*

These two non-functional requirements critical for legal reasons. As The Phoenix is on McMaster property, it must comply with the by-laws created and enforced by the university. As The Phoenix is also a bar with a liquor license it is also critical that they operate their business with respect to the by-laws and regulations of the Ontario Government.

