[#s1,reftext=S.1]
=== (S.1) Components

ifdef::env-draft[]
TIP: _Overall structure expressed by the list of major software and, if applicable, hardware parts._  <<BM22>>
endif::[]

The system relies on the following four software components:

* **`Patron Manager`**: The component in charge of managing the patrons database (`Manage Patrons`), as well as providing services related to the loyalty program (`Loyalty`). It centralizes the business logic related to customer management in *{project-title}*.
* **`Menu Provider`**: The component in charge of exposing the menu to the patrons using the system. It exposes an administration interface (`Manage Menu`), as well as a way to seach for items (`Lookup`). The component focuses only on what is available for *{project-title}*, and will not contain 100% of the restaurant menu.
* **`Order Manager`**: The component in charge of processing orders made through the system (`Process Order`). It implements the business logic related to selling goods (mealboxes or catering services), and listing elements to be cooked by the kitchen (`List Impeding`).
* **`Billing`**: The component acting as an integrated gateway to external payment services (`Process Payment`) and internal meal plans (`MealPlan Payment`). It also exposes a way to collect `Pending Invoices` when requested, to support interaction with <<mosaic>>.

In addition to these components, the system will interact with two external components to support integration with <<mosaic>> and payment processing (see <<e2>> for details). 

Patrons use a mobile application to interact with the system, for the loyalty program as well as ordering meal boxes. Restaurant staff use a web-based system to administrate the system (patrons database, catering orders). It is important to note that Administrative Staff does not interact directly with the system, and will continue ordering catering or booking tables by phone or email

.Components involved in {project-title} mobile app
image::models/component_mobile.svg[scale=75%,align="center"]

.Components involved in {project-title} administration (web) app
image::models/component_web.svg[scale=75%,align="center"]