[#s2,reftext=S.2]
=== (S.2) Functionality

ifdef::env-draft[]
TIP: _**This is the bulk of the System book, describing elements of functionality (behaviors)**. This chapter corresponds to the traditional view of requirements as defining "**what the system does**”. It is organized as one section, S.2.n, for each of the components identified in <<s1>>, describing the corresponding behaviors (functional and non-functional properties)._  <<BM22>>
endif::[]

==== (S.2.1) Patron Manager
===== Functional Requirements

. **Sign-up service**: Patron manager shall allow customers the option to sign-up and create an account to gain access to the loyalty program.

. **Sign-up service**: Patron manager shall allow customers the option to sign-up and create an account to gain access to the loyalty program.

. **Log-in/out service**: Patron manager shall allow customers to login and logout when desired without losing and points previously earned.

. **Check loyalty status**: Patron manager shall allow customers to check the status of their loyalty points including points until next available reward.

. **Password recovery**: Patron manager shall allow customers to recover password in the event they have forgotten their login information.

===== Non-Functional Requirements

. **Logo location**: Patron manager shall display the Firebird logo to customers while accessing services.

. **Text size and color**: Patron manager shall provide options to change font color and size to facilitate legibility of on-screen information.

==== (S.2.2) Menu Provider

===== Functional Requirements

. **Provide menu**: Menu manager shall provide customer with access to the menu so that they can choose their desired item for order.

. **Search through menu**: Menu manager shall provide customer with the ability to lookup specific items in the menu.

. **Update menu provider**: Menu manager shall provide an interface to staff to update the menu with new items or remove old ones.

. **Select menu item**: Menu manager shall allow customers to select the items that they wish to purchase.

===== Non-Functional Requirements

. **Legibility**: Menu manager shall space out menu items consistently to facilitate reading and understanding of on-screen information.

. **Pictures of food**: Menu manager shall provide some pictures of menu items to entice customers to purchase food that looks particularly delicious.

==== (S.2.3) Order Manager

===== Functional Requirements

. **Complete food order (Process Order)**: Order manager shall provide customer with an interface to complete food order purchase.

. **Receive food order**: Order manager shall provide line cook with ordered list of food that requires cooking and preparation.

. **Food order complete**: Order manager shall provide line cook with interface to state when food cooking is complete. This will also prompt user with notification when food cooking is complete

. **Catering order (Process Order)**: Order manager shall provide contact information to staff that wish to order catering for an event.

===== Non-Functional Requirements

. **Push notifications**: Order manager shall by default enable push notifications from the app to customer phone. 

. **Cart management**: Order manager shall provide a helpful interface for users to manage/modify their orders during the ordering process.

==== (S.2.4) Billing

===== Functional Requirements

. **Order payment (Process Payment)**: Billing shall provide user with an interface to pay for their order using an external payment service.

. **Order payment (MealPlan Payment)**: Billing shall provide customer with an interface to pay for their order using their student meal plan card.

. **Order payment (Pending Invoices)**: Billing shall provide restaurant manager with an interface to create invoices for catering orders using department number of faculty.

. **Sales reports**: Billing shall provide restaurant manager with an interface to request and review sales reports though the app.

. **Use loyalty points**: Billing shall prompt user if they want to use loyalty points (if they have enough) before completing payment.

. **Email purchase receipt**: Billing shall email customer the receipt upon payment completed

===== Non-Functional Requirements

. **Save payment option**: Billing shall prompt the user to have the option to save their payment option for future purchases.

. **Email receipt opt-out**: Billing shall provide the option to the user to opt-out of getting email receipts.
