[#s2,reftext=S.2]
=== (S.2) Functionality

ifdef::env-draft[]
TIP: _**This is the bulk of the System book, describing elements of functionality (behaviors)**. This chapter corresponds to the traditional view of requirements as defining "**what the system does**”. It is organized as one section, S.2.n, for each of the components identified in <<s1>>, describing the corresponding behaviors (functional and non-functional properties)._  <<BM22>>
endif::[]

==== (S.2.1) Patron Manager
===== Functional Requirements
====== (S.2.1.1) Sign-up service
Patron manager shall allow customers the option to sign-up and create an account to gain access to the loyalty program.

====== (S.2.1.2) Log-in/out service
Patron manager shall allow customers to login and logout when desired without losing and points previously earned.

====== (S.3.1.3) Check loyalty status
Patron manager shall allow customers to check the status of their loyalty points including points until next available reward.

====== (S.2.1.4) Password recovery
Patron manager shall allow customers to recover password in the event they have forgotten their login information.

===== Non-Functional Requirements

====== (S.2.1.5) Logo location
Patron manager shall display the Firebird logo to customers while accessing services.

====== (S.2.1.6) Text size and color
Patron manager shall provide options to change font color and size to facilitate legibility of on-screen information.

==== (S.2.2) Menu Provider

===== Functional Requirements

====== (S.2.2.1) Provide menu
Menu manager shall provide customer with access to the menu so that they can choose their desired item for order.

====== (S.2.2.2) Search through menu
Menu manager shall provide customer with the ability to lookup specific items in the menu.

====== (S.2.2.3) Update menu provider
Menu manager shall provide an interface to staff to update the menu with new items or remove old ones.

===== Non-Functional Requirements

====== (S.2.2.4) Legibility
Menu manager shall space out menu items consistently to facilitate reading and understanding of on-screen information.

====== (S.2.2.5) Pictures of food
Menu manager shall provide some pictures of menu items to entice customers to purchase food that looks particularly delicious.

==== (S.2.3) Order Manager

===== Functional Requirements

====== (S.2.3.1) Complete food order (Process Order)
Order manager shall provide customer with an interface to complete food order purchase.

====== (S.2.3.2) Receive food order
Order manager shall provide line cook with ordered list of food that requires cooking and preparation.

====== (S.2.3.3) Food order complete
Order manager shall provide line cook with interface to state when food cooking is complete. This will also prompt user with notification when food cooking is complete

====== (S.2.3.4) Catering order (Process Order)
Order manager shall provide contact information to staff that wish to order catering for an event.

===== Non-Functional Requirements

====== (S.2.3.5) Push notifications
Order manager shall by default enable push notifications from the app to customer phone. 

====== (S.2.3.6) Cart management
Order manager shall provide a helpful interface for users to manage/modify their orders during the ordering process.

==== (S.2.4) Billing

===== Functional Requirements
====== (S.2.4.1) Order payment (Process Payment)
Billing shall provide customer with an interface to pay for their order using an external payment service.

====== (S.2.4.2) Order payment (MealPlan Payment)
Billing shall provide customer with an interface to pay for their order using their student meal plan card.

====== (S.2.4.3) Order payment (Pending Invoices)
Billing shall provide staff with an interface to pay for their catering order using department of faculty number.

====== (S.2.4.4) Sales reports 
Billing shall provide restaurant manager with an interface to request and review sales reports though the app.

====== (S.2.4.5) Use loyalty points
Billing shall prompt user if they want to use loyalty points (if they have enough) before completing payment.

====== (S.2.4.6) Email purchase receipt
Billing shall email customer/staff the receipt upon payment completed

===== Non-Functional Requirements
====== (S.2.4.7) Save payment option
Billing shall prompt the user to have the option to save their payment option for future purchases.

====== (S.2.4.8) Email receipt opt-out
Billing shall provide the option to the user to opt-out of getting email receipts.
