[#p5,reftext=P.5]
=== (P.5) Required technology elements

ifdef::env-draft[]
TIP: _External systems, hardware and software, expected to be necessary for building the system. It lists external technology elements, such as program libraries and hardware devices, that the project is expected to require. Although the actual use of such products belongs to design and implementation rather than requirements, it is part of the requirements task to identify elements whose availability is critical to the success of the project — an important element of risk analysis (<<p6>>)._  <<BM22>>
endif::[]

- Compliance with external API for <<mosaic>>
-- This is critical for integration with existing systems.
- Compliance with external API for Payment Gateway
-- This is critical to enable payment options and acceptance from customers when they order food.
- IoT physical button to support LineCook
-- This is a suggest approach for how we can more easily integrate features from the app, such as food complete notifications, with the way the kitchen works for the restaurant.