[#p6,reftext=P.6]
=== (P.6) Risk and mitigation analysis

ifdef::env-draft[]
TIP: _Potential obstacles to meeting the schedule of <<p4>>, and measures for adapting the plan if they do arise. It is essential to be on the lookout for events that could derail the project, and devise mitigation strategies. It can include a SWOT analysis (Strengths, Weaknesses, Opportunities, Threats) for the project._  <<BM22>>
endif::[]

Some of the risks present during development are listed below:

* *Difficulties integrating with <<mosaic>>.* One major aspect of this project is integration with existing infrastructure at McMaster. Thus this will require close work with the system administrator for <<mosaic>>. In the event that documentation on the system is poor, or it becomes difficult to get a representative to work with it can be extremely difficult to accomplish the integrations on schedule. One mitigation strategy for this would be to start working on integration from the start of the project, in parallel to the actual application. This would allow more time to documentation to be provided, and ideally allow for more flexibility to get a representative from the administration team to assist with the integration without taking away too much time from their primary responsibilities.

* *Competition with Heavenly catering.* Heavenly catering already has a monopoly for catering on campus. Thus they can present a hurdle to the completion of the application by attempting to stall it or get it shut down altogether. This can be mitigated by involving high level McMaster administration to ensure that we have the university support for developing the application, as well as getting support from various faculty to support more competition for catering services on campus.

