[#e1,reftext=E.1]
=== (E.1) Glossary

ifdef::env-draft[]
TIP: _Clear and precise definitions of all the vocabulary specific to the application domain, including technical terms, words from ordinary language used in a special meaning, and acronyms. It introduces the terminology of the project; not just of the environment in the strict sense, but of all its parts._  <<BM22>>
endif::[]

[[mosaic,Mosaic]] Mosaic (Information System)::
    Mosaic is McMaster's internal portal. It acts as a unique entry point aggregating each and every tool used to support McMaster's community. Students use it for course enrollment, staff for expense reports, faculty for accessing class rosters. Acting as a portal, it covers Student Administration, Finance, HR, Research Administration, and Facilities Maintenance Management.

[[staff,Staff]] Staff::
    When referring to _staff_, this document refers to persons employed by McMaster to support its operations, who might commit to expenses in food and hospitality. This generally includes administration staff and full-time faculty members. 

[[community,Community]] McMaster community::
    McMaster's community includes <<staff>>, as well as students (undergrad and graduate ones).

[[catering,Catering]] Catering Services::
    McMaster operates its own internal catering system, in compliance of the by-laws controlling food operations on campus grounds. Extensive information of Catering operations can be found here: https://hospitality.mcmaster.ca/catering-gifts/catering-services/

[[uts,UTS]] University Technology Service::
    McMaster internal IT service, in charge of operating its technological infrastructure. It includes, among others, <<macid>>, <<Mosaic>>, Avenue to Learn (course management system).

[[macid,MacID]] MacID::
    Mac ID is the local _Single Sign On_ (SSO) deployed as McMaster as a unique and centralized way to support authentication among the different apps used by the university (_e.g._, <<mosaic>>, Avenue to Learn)

[[mealplan,Meal Plan]] Meal Plan::
    The meal plan is an opt-in option that the majority of students who live in residence take to get meals, and is continually offered to all students. They are able to prepay money to their Mosaic account and use their student card to purchase food on campus, or other local restaurants that accept student meal plans as a form of payment.