[#e2,reftext=E.2]
=== (E.2) Components

ifdef::env-draft[]
TIP: _List of elements of the environment that may affect or be affected by the system and project. It includes other systems to which the system must be interfaced. These components may include existing systems, particularly software systems, with which the system will interact — by using their APIs (program interfaces), or by providing APIs to them, or both. These are interfaces provided to the system from the outside world. They are distinct from both: interfaces provided by the system to the outside world (<<s3>>); and technology elements that the system's development will require (<<p5>>)._  <<BM22>>
endif::[]

The system interacts with two external components:

- **`Mosaic`**: The component hosted by <<uts>> and providng services related to McMaster processes, such as meal plan and supporting internal billing. This legacy compomnent is out of scope for *{project-title}*, which needs to interact with it.

- **`Payment Gateway`**: The component implementing the interface from the payment provider used to process payments (Visa, Mastercard, GoogleWallet, ApplePay). As the provider is not selected yet, we assume here a "global" interface which is compatible with out preliminary study of the provider market.


