[#e3,reftext=E.3]
=== (E.3) Constraints

ifdef::env-draft[]
TIP: _Obligations and limits imposed on the project and system by the environment. This chapter defines non-negotiable restrictions coming from the environment (business rules, physical laws, engineering decisions), which the development will have to take into account._  <<BM22>>
endif::[]

- **Interactions with <<mosaic>>**: To support a meal plan debit, *{project-title}* needs to send a request for payment to the system Internal billing works the other way around: the system exposes an endpoint providing pending invoices, and periodically <<mosaic>> collect them and start the accounting reconciliation process.

- **Mobile support**: The system must work with classical smartphone, _i.e._, Apple and Android devices and comply with app store policy.

- **Internet support**: The system must work with internet browsers (_i.e._, Chrome, Safari, Edge) to support staff and in the event that customers do no wish to download the app.
