[#e5,reftext=E.5]
=== (E.5) Effects

ifdef::env-draft[]
TIP: _Elements and properties of the environment that the system will affect. It defines effects of the system's operations on properties of the environment. Where the previous two categories (<<e3>>, <<e4>>) defined influences of the environment on the system, effects are influences in the reverse direction._  <<BM22>>
endif::[]

Some of the potential effects of the application can be defined as follows:

- Increase in student happiness, health, and morale. This is possible due through the facilitation of access to food, preventing students from having to make the choice to eat or attend class. It can also promote more social interactions among the student population through easier catering options or just promoting more attractions of the
The FireBird.

- Increase in on-campus student population. This is possible as the app may promote more reasons for students to be on campus through the loyalty program that rewards them for their in person patronage, even if it's just by picking up their orders.

- Increase in events on campus. This is possible through integration with staff on campus and allowing seamless payment through departments, faculties, and clubs. This would also promote competition on campus, potentially allowing for better prices on catering for events or better quality food for catered events.

