@startuml

!include ../_style/puml.style
skinparam ranksep  5
skinparam nodesep 45

' ***********************
' * External Components *
' ***********************

component mosaic       as "Mosaic" <<external>>
() "MealPlan\nPayment" as Imeal_plan
mosaic -- Imeal_plan

component payment     as "Payment\nGateway" <<external>>
() "Process\nPayment" as Iprocess_payment
Iprocess_payment -- payment 


' ***********************
' * Internal Components *
' ***********************

component menu    as "Menu\nProvider"
() "Lookup"       as Imenu_lookup
() "Manage\nMenu" as Imenu_mgmt
menu -- Imenu_lookup
Imenu_mgmt - menu

component billing    as "Billing"
() "BillOrder"       as Ibilling
() "Pending\nInvoices" as Ipending
billing ..> Iprocess_payment
Imeal_plan <.. billing
Ibilling - billing
billing - Ipending


component patrons as "Patron\nManager"
() "Loyalty"      as Iloyalty
Iloyalty -- patrons
() "Manage\nPatrons" as Ipatrons_mgmt
Ipatrons_mgmt - patrons

component ordering as "Order\nManager"
() "Process\nOrder" as Iprocess_order
ordering .> Ibilling
Iprocess_order - ordering
() "ListImpeding" as Ilist_impeding
Ilist_impeding -- ordering


' **************
' * client app *
' **************

component mobile as "ClientApp"
Imenu_lookup <.. mobile
mobile ..> Iloyalty
mobile .> Iprocess_order

actor "Patron" as P
P .> mobile

@enduml
  