@startuml

!include ../_style/puml.style
skinparam ranksep  5
skinparam nodesep 45

' ***********************
' * Internal Components *
' ***********************

component menu    as "Menu\nProvider"
() "Lookup"       as Imenu_lookup
() "Manage\nMenu" as Imenu_mgmt
Imenu_lookup - menu
menu -- Imenu_mgmt

component billing    as "Billing"
() "BillOrder"       as Ibilling
() "Pending\nInvoices" as Ipending
Ibilling - billing
Ipending -- billing


component patrons as "Patron\nManager"
() "Loyalty"      as Iloyalty
Iloyalty -- patrons
() "Manage\nPatrons" as Ipatrons_mgmt
Ipatrons_mgmt - patrons

component ordering as "Order\nManager"
() "Process\nOrder" as Iprocess_order
() "ListImpeding" as Ilist_impeding
ordering .> Ibilling
Ilist_impeding - ordering
Iprocess_order -- ordering

' ***********************
' * External Components *
' ***********************

component mosaic       as "Mosaic" <<external>>
Ipending <. mosaic


' **************
' * client app *
' **************

component "Web\nAdmin" as web
Actor "Restaurant\nStaff" as S

S .> web
web .> Ipatrons_mgmt
Imenu_mgmt <.. web
web ..> Iprocess_order
web ..> Ilist_impeding

@enduml
  